### ISSUE TITLE
Why Chromium

### ISSUE THREAD

**Issue by arcaela** [ChrisMichaelPerezSantiago/ryuanime#288]
Why Chromiun is downloading when install packages??

**Comment by chrismichaelps** [comment]
_Hi @arcaela ,_

_Sorry for the delay,_

_To be honest, it's been a long time since I stopped maintaining the project._
_Sorry for the inconvenience._

**Comment by arcaela** [comment]
Oh! that ok, dont worry.

I did use this project yesterday for some api, i like this. but i dont know how run "npm run install" without Downloading Chromiun, but is excelent project.

**Comment by arcaela** [comment]
> Oh! that ok, dont worry.
> 
> I did use this project yesterday for some api, i like this. but i dont know how run "npm run install" without Downloading Chromiun, but is excelent project.

sorry for my english

**Comment by chrismichaelps** [comment]
_I see what you want to tell me,_


_What happens is that I had installed the puppeteer package to do an automated scraping under chrome, but don't use that package since there is a better solution with cheerio._

_I had forgotten to remove the puppeteer package, since I do not use it and apart from the download size it is a bit excessive and makes the repo weigh more than it should._

**Comment by chrismichaelps** [comment]
_If you downloaded the repository earlier, you can uninstall the puppeteer package by typing the following in the terminal._

```shell
npm uninstall puppeteer
```

**Comment by chrismichaelps** [comment]
_If you are interested in using the API, I created an improved version separately in another [repository](https://github.com/ChrisMichaelPerezSantiago/jkanime)_

_I also have another API developed from **animeflv** that is quite complete and I must say much better than **jkanime**. Here I leave you the [URL](https://github.com/ChrisMichaelPerezSantiago/animeflv) in case you are interested in seeing it._

**Comment by arcaela** [comment]
Yes, i been see.
But need embed media player.

**Comment by arcaela** [comment]
and where is documentation for animeflv?

**Comment by arcaela** [comment]
Is done, and is awesome...
If you have bitcoin wallet i can send u some satoshis, is excelent work

**Comment by chrismichaelps** [comment]
thanks

_This is my bitcoin wallet adress `1JhjCtxPpqdvmpYz3QP4QscugyJM35Gs2r`_

_Or you can donate through [paypal](https://www.paypal.me/chrismperezsantiago?locale.x=en_US)_
